// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Entities;

public partial class Store
{
    public Guid Id { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public string ThumbnailUrl { get; set; }

    public string Address { get; set; }

    public virtual ICollection<Product> Products { get; set; } = new List<Product>();

    public virtual StoreOwner StoreOwner { get; set; }
}