// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Entities;

public partial class StoreOwner
{
    public Guid Id { get; set; }

    public string Email { get; set; }

    public string Password { get; set; }

    public string Phone { get; set; }

    public string Name { get; set; }

    public string AvatarUrl { get; set; }

    public Guid? StoreId { get; set; }

    public string Status { get; set; }

    public virtual ICollection<MembershipTransaction> MembershipTransactions { get; set; } = new List<MembershipTransaction>();

    public virtual Store Store { get; set; }

    public virtual ICollection<StoreOwnerMembership> StoreOwnerMemberships { get; set; } = new List<StoreOwnerMembership>();
}